### ISSUE TITLE
Are there any plans to update to 0.12.x?

### ISSUE THREAD

**Issue by dfbernal** [onyx-platform/onyx-plugin#4]

**Comment by lbradstreet** [comment]
Hi @dfbear.

Yes, we are just a little stretched for time at the moment. Are you interested in writing a plugin? If so, I can accelerate updating it for 0.12.x.

Lucas

**Comment by dfbernal** [comment]
I'm currently working on updating the Elasticsearch plugin to support a later version of ES. There were a few differences between the plugin frameworks but I managed to get it to work by looking at other plugins. It'd be useful to have the template just so that I can feel a little bit more satisfied with its organization but it's not totally necessary.

**Comment by lbradstreet** [comment]
Thanks to the hard work of @quimrstorres, the plugin template has been updated for 0.12!
